INSERT INTO products (name, description, material, img, category, price) VALUES
('Raquel', 'Raquel es un totem. Es una muñeca de apego que te va a guiar en los momentos difíciles, como una brújula en un mar agitado y oscuro',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '002.jpeg', 'muñecas', '34000'),
 ('Marcela', 'Marcela despierta tu lado mas tierno. Una muñeca para conectar cone se nucleo sensible, con ese niño interior que todos tenemos dentro y dejarlo salir a jugar',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '003.jpeg', 'muñecas', '34000'),
 ('Raquel', 'Raquel es un totem. Es una muñeca de apego que te va a guiar en los momentos difíciles, como una brújula en un mar agitado y oscuro',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '004.jpeg', 'ovejas', '23500'),
 ('Marcela', 'Marcela despierta tu lado mas tierno. Una muñeca para conectar cone se nucleo sensible, con ese niño interior que todos tenemos dentro y dejarlo salir a jugar',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '005.jpeg', 'ovejas', '28000'),
 ('Raquel', 'Raquel es un totem. Es una muñeca de apego que te va a guiar en los momentos difíciles, como una brújula en un mar agitado y oscuro',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '006.jpeg', 'animales', '34000'),
 ('Marcela', 'Marcela despierta tu lado mas tierno. Una muñeca para conectar cone se nucleo sensible, con ese niño interior que todos tenemos dentro y dejarlo salir a jugar',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '008.jpeg', 'animales', '34000'),
 ('Raquel', 'Raquel es un totem. Es una muñeca de apego que te va a guiar en los momentos difíciles, como una brújula en un mar agitado y oscuro',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '009.jpeg', 'animales', '34000'),
 ('Marcela', 'Marcela despierta tu lado mas tierno. Una muñeca para conectar cone se nucleo sensible, con ese niño interior que todos tenemos dentro y dejarlo salir a jugar',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '001.jpeg', 'ovejas', '28000'),
 ('Juanita', 'Marcela despierta tu lado mas tierno. Una muñeca para conectar cone se nucleo sensible, con ese niño interior que todos tenemos dentro y dejarlo salir a jugar',
 'Confeccionada en liencillo de algodón de alta calidad. Lanas naturales. Pintura para tela. Pasamanería vintage y de diseño', 
 '010.jpeg', 'ovejas', '23500');

 
